import { expect, test, describe } from "bun:test"
import { createKicadLibraryZip } from "lib/optional-features/exporting/formats/export-kicad-library"
import * as fs from "node:fs"
import * as path from "node:path"

// Read the STEP file content for the mock server
const stepFilePath = path.join(
  process.cwd(),
  "examples/assets/SW_Push_1P1T_NO_CK_KMR2.step",
)
const stepFileContent = fs.readFileSync(stepFilePath)

// Sample circuit JSON that would be generated by tscircuit
// This includes the structure needed to test footprint and symbol extraction
// with 3D model support (using model_step_url and pcb_component_id on cad_component)
const createSampleCircuitJson = (modelUrl: string) => [
  // Source components
  {
    type: "source_component",
    source_component_id: "source_component_0",
    name: "R1",
    ftype: "simple_resistor",
    resistance: 1000,
  },
  {
    type: "source_component",
    source_component_id: "source_component_1",
    name: "C1",
    ftype: "simple_capacitor",
    capacitance: 0.0000001,
  },
  {
    type: "source_component",
    source_component_id: "source_component_2",
    name: "SW1",
    ftype: "simple_push_button",
  },
  // PCB components
  {
    type: "pcb_component",
    pcb_component_id: "pcb_component_0",
    source_component_id: "source_component_0",
    center: { x: 5, y: 0 },
    rotation: 0,
    layer: "top",
    width: 1,
    height: 0.5,
  },
  {
    type: "pcb_component",
    pcb_component_id: "pcb_component_1",
    source_component_id: "source_component_1",
    center: { x: -5, y: 0 },
    rotation: 0,
    layer: "top",
    width: 1.6,
    height: 0.8,
  },
  {
    type: "pcb_component",
    pcb_component_id: "pcb_component_2",
    source_component_id: "source_component_2",
    center: { x: 0, y: 5 },
    rotation: 0,
    layer: "top",
    width: 5,
    height: 4,
  },
  // CAD component with 3D model - must have pcb_component_id and model_step_url
  ...(modelUrl
    ? [
        {
          type: "cad_component",
          cad_component_id: "cad_component_0",
          pcb_component_id: "pcb_component_2",
          model_step_url: modelUrl,
          position: { x: 0, y: 5, z: 0 },
          rotation: { x: 0, y: 0, z: 0 },
        },
      ]
    : []),
  // SMT pads for footprints
  {
    type: "pcb_smtpad",
    pcb_smtpad_id: "pcb_smtpad_0",
    pcb_component_id: "pcb_component_0",
    shape: "rect",
    x: 4.5,
    y: 0,
    width: 0.4,
    height: 0.4,
    layer: "top",
  },
  {
    type: "pcb_smtpad",
    pcb_smtpad_id: "pcb_smtpad_1",
    pcb_component_id: "pcb_component_0",
    shape: "rect",
    x: 5.5,
    y: 0,
    width: 0.4,
    height: 0.4,
    layer: "top",
  },
  {
    type: "pcb_smtpad",
    pcb_smtpad_id: "pcb_smtpad_2",
    pcb_component_id: "pcb_component_1",
    shape: "rect",
    x: -5.5,
    y: 0,
    width: 0.5,
    height: 0.5,
    layer: "top",
  },
  {
    type: "pcb_smtpad",
    pcb_smtpad_id: "pcb_smtpad_3",
    pcb_component_id: "pcb_component_1",
    shape: "rect",
    x: -4.5,
    y: 0,
    width: 0.5,
    height: 0.5,
    layer: "top",
  },
  {
    type: "pcb_smtpad",
    pcb_smtpad_id: "pcb_smtpad_4",
    pcb_component_id: "pcb_component_2",
    shape: "rect",
    x: -1,
    y: 5,
    width: 0.6,
    height: 0.6,
    layer: "top",
  },
  {
    type: "pcb_smtpad",
    pcb_smtpad_id: "pcb_smtpad_5",
    pcb_component_id: "pcb_component_2",
    shape: "rect",
    x: 1,
    y: 5,
    width: 0.6,
    height: 0.6,
    layer: "top",
  },
  // Schematic components
  {
    type: "schematic_component",
    schematic_component_id: "schematic_component_0",
    source_component_id: "source_component_0",
    center: { x: 0, y: 0 },
    rotation: 0,
    size: { width: 1, height: 0.5 },
    symbol_name: "boxresistor",
  },
  {
    type: "schematic_component",
    schematic_component_id: "schematic_component_1",
    source_component_id: "source_component_1",
    center: { x: 3, y: 0 },
    rotation: 0,
    size: { width: 1, height: 0.5 },
    symbol_name: "capacitor",
  },
  {
    type: "schematic_component",
    schematic_component_id: "schematic_component_2",
    source_component_id: "source_component_2",
    center: { x: 6, y: 0 },
    rotation: 0,
    size: { width: 2, height: 2 },
    symbol_name: "unknown",
  },
]

describe("KiCad Library Export", () => {
  test("createKicadLibraryZip generates symbol library and footprints", async () => {
    const circuitJson = createSampleCircuitJson("")
    const libraryName = "test-library"

    const zip = await createKicadLibraryZip({
      circuitJson: circuitJson as any,
      libraryName,
    })

    const files = Object.keys(zip.files)
    console.log("Generated files:", files)

    // Check symbol library exists
    const symFile = zip.file(`${libraryName}.kicad_sym`)
    expect(symFile).toBeDefined()
    const symContent = await symFile?.async("string")
    expect(symContent).toBeTruthy()
    expect(symContent).toContain("kicad_symbol_lib")

    // Check footprint library folder exists with footprints
    const footprintFiles = files.filter((f) => f.endsWith(".kicad_mod"))
    console.log("Footprint files:", footprintFiles)
    expect(footprintFiles.length).toBeGreaterThanOrEqual(1)

    // Check library tables exist
    const fpLibTable = zip.file("fp-lib-table")
    const symLibTable = zip.file("sym-lib-table")
    expect(fpLibTable).toBeDefined()
    expect(symLibTable).toBeDefined()

    const fpLibTableContent = await fpLibTable?.async("string")
    const symLibTableContent = await symLibTable?.async("string")
    expect(fpLibTableContent).toContain("fp_lib_table")
    expect(fpLibTableContent).toContain(libraryName)
    expect(symLibTableContent).toContain("sym_lib_table")
    expect(symLibTableContent).toContain(libraryName)

    // Check footprints have proper content
    const footprintContent = await zip
      .file(footprintFiles[0])
      ?.async("string")
    expect(footprintContent).toContain("footprint")
    expect(footprintContent).toContain("pad")
  }, 30000)

  test("createKicadLibraryZip fetches and includes 3D model files", async () => {
    // Start a simple HTTP server to serve the STEP file
    const server = Bun.serve({
      port: 0,
      fetch(req) {
        const url = new URL(req.url)
        if (url.pathname === "/SW_Push_1P1T_NO_CK_KMR2.step") {
          return new Response(stepFileContent, {
            headers: { "Content-Type": "application/octet-stream" },
          })
        }
        return new Response("Not found", { status: 404 })
      },
    })

    try {
      const stepFileUrl = `http://localhost:${server.port}/SW_Push_1P1T_NO_CK_KMR2.step`
      const circuitJson = createSampleCircuitJson(stepFileUrl)
      const libraryName = "test-library"

      const zip = await createKicadLibraryZip({
        circuitJson: circuitJson as any,
        libraryName,
      })

      const files = Object.keys(zip.files)
      console.log("Generated files with 3D model:", files)

      // Check 3D model file is included
      const shapesFolder = `${libraryName}.3dshapes/`
      const modelFiles = files.filter(
        (f) => f.startsWith(shapesFolder) && f.endsWith(".step"),
      )
      console.log("3D model files:", modelFiles)

      // The model should be fetched and included
      expect(modelFiles.length).toBeGreaterThanOrEqual(1)

      const modelContent = await zip.file(modelFiles[0])?.async("arraybuffer")
      expect(modelContent).toBeDefined()
      expect(modelContent!.byteLength).toBeGreaterThan(0)
      console.log("3D model size:", modelContent!.byteLength, "bytes")

      // Verify it's the actual STEP file content
      expect(modelContent!.byteLength).toBe(stepFileContent.byteLength)

      // Verify footprint contains model reference
      const pushButtonFootprint = await zip
        .file("test-library.pretty/simple_push_button.kicad_mod")
        ?.async("string")
      expect(pushButtonFootprint).toContain("(model")
      expect(pushButtonFootprint).toContain("test-library.3dshapes")
    } finally {
      server.stop()
    }
  }, 30000)
})
